services:
  php:
    working_dir: /var/www/weather
    build:
      context: './docker/php/'
    volumes:
      - '.:/var/www/weather'
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    command: sh -c "php bin/console app:weather:fetch && php -S 0.0.0.0:8000 -t public"
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}